# Site settings
title:       TIL
email:       bernardo.amc@gmail.com
author:      Bernardo Chaves
description: 'Things learned. Share all the things.'
baseurl:     ""
url:         'http://l:4000'

# Google analytics
google_analytics: 'UA-3572676-15'

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     20
sass:
  compressed: true
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']
