# Site settings
title:       TIL
description: 'Things learned. Share all the things.'
baseurl:     ""
url:         'http://shareallthethings.com'

# Google analytics
google_analytics: 'UA-3572676-15'

# Build settings
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 's3_website.yml']
permalink: pretty
paginate: 20

gems:
- jekyll-assets
- jekyll-paginate

# markup processors
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
