# Site settings
title:       'ShareAllTheThings'
description: 'Today I Learned.'
baseurl:     ""
url:         'http://shareallthethings.com'

# Google analytics
google_analytics: 'UA-3572676-15'

# Build settings
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 's3_website.yml']
permalink: pretty
paginate: 20

gems:
  - jekyll-assets
  - jekyll-paginate

# markup processors
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']

# Assets
assets:
  compress:
    css: true
    js: true
  prefix: "/assets"
  digest: true
